# Generated by Django 2.2.4 on 2021-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210723_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='cOd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_image', models.ImageField(upload_to='blog/target')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
