# Generated by Django 2.2.4 on 2021-08-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='check_image',
            field=models.ImageField(upload_to='cod'),
        ),
    ]
