# Generated by Django 2.2.4 on 2021-08-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210809_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cOd',
            new_name='Checkimage',
        ),
    ]
