# Generated by Django 2.2.4 on 2021-08-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210809_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkimage',
            name='check_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
