# Generated by Django 2.2.4 on 2021-08-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210810_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkimage',
            name='check_image',
            field=models.ImageField(upload_to='target'),
        ),
    ]
