# Generated by Django 3.2.6 on 2021-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210813_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkimage',
            name='check_value',
            field=models.FloatField(default=0.0),
        ),
    ]
