# Generated by Django 3.2.6 on 2021-08-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_checkimage_check_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkimage',
            name='check_value',
        ),
    ]
