# Generated by Django 3.2.6 on 2021-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_checkimage_check_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkimage',
            name='pred_val',
            field=models.FloatField(default=2.0),
        ),
    ]
