# Generated by Django 3.2.6 on 2021-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_checkimage_pred_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAndDogApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_image', models.ImageField(upload_to='target')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('pred_val', models.FloatField(default=2.0)),
            ],
        ),
    ]
