# Generated by Django 3.2.6 on 2021-08-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_catanddogapi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatAndDogApi',
            new_name='CatAndDogUploadApi',
        ),
    ]
